### ISSUE TITLE
Prevayler in Docker volumes howto

### ISSUE THREAD

**Issue by McPringle** [jsampson/prevayler#13]
I manage several open source projects where we use Prevailer for persistence management. These projects now use Docker and volume mapping. What is the best way to keep several running instances (scaling, several containers on multiple hosts) in sync using Prevailer?

Actually we nail the maximum container count per app down to one which is not satisfying (no scaling).

**Comment by jsampson** [comment]
This would be a great question to post on the mailing list, where it will get more attention: https://lists.sourceforge.net/lists/listinfo/prevayler-discussion

**Comment by karlwettin** [comment]
There is nothing in the distribution that does sync over multiple instances, but not too long ago I posted a short thing on the mailling list regarding that I'm running an ad hoc prevalance jounral via a message queue to keep multiple kubernetes pods on gcloud synced.

Compared to using Prevayler this is great for handling if/when a pod goes down, but is terrible for transaction write speed.

https://sourceforge.net/p/prevayler/mailman/message/35721959/
